"""Exceptions métier — TAC MP4 Studio."""
from __future__ import annotations


class TACError(Exception):
    def __init__(self, message: str, detail: str = "") -> None:
        super().__init__(message)
        self.message = message
        self.detail = detail


class AudioImportError(TACError): ...
class ImageImportError(TACError): ...
class RenderError(TACError): ...
class ExportError(TACError): ...
class FFmpegError(TACError): ...
class ConfigError(TACError): ...
class PresetError(TACError): ...
class PreviewError(TACError): ...
